### PR TITLE
Copy from SpenceKonde/ATTinyCore

### PR DESCRIPTION
**Pull request by pcfreak1201**
Can't *burn bootloader* over USB or *upload with programmer* when wrong bootloader is installed.
So with this option it is possible, or isn't it?

### CODE REVIEW

**Comment by ArminJo** [comment]
Thanks 👍 
But it tooks more than just extending this file.
It would be great, if you can do a Quality Assurance for the commit 🙏

**Comment by pcfreak1201** [comment]
Hallo Armin!
Year, it really tooks more - but may be there is also still a "problem" with external programmers and @SpenceKonde s  config in ATTinyCore. I try it parallel in ATTinyCore and DigistumpArduino with a t85 and I realized when I "Burn Bootloader" with USBAsp selected, I get:
```
avrdude: verifying ...
avrdude: 1 bytes of efuse verified
avrdude: reading input file "0b11011{bootloader.bod_bits}"
avrdude: invalid byte value (0b11011{bootloader.bod_bits}) specified for immediate mode
avrdude: read from file '0b11011{bootloader.bod_bits}' failed
```
(because I set BOD to 4V3=0b100 ?) So may be there is a parsing-problem with {bootloader.bod_bits}?

But anyway, I changed/added some files/parts from ATTinyCore:
https://github.com/ArminJo/DigistumpArduino/compare/master...pcfreak1201:master
and could now "Upload with Programmer". 
But also trying to set the fuse manual/external to E:0xFE H:0xDC L:0xF1 (USB-Bootloader) still doesn't work.
I think I have to investigate more/deeper - possibly it will be necessary to add a "Burn Bootloader Method" menu.

**Comment by ArminJo** [comment]
Can you please specify clearer for which core you get the Fuse problem? DigistumpArduino does not intend try to set any fuses.

**Comment by pcfreak1201** [comment]
Just now, it works!?
I just reflash digistump/hardware/avr/1.7.2/bootloaders/upgrade-t85_entry_on_powerOn_activePullup_fastExit.hex
... and now it uploads! Looks like hardware-problems with blocking my ports after too much flashing.

The reason for my tries is simple: it was an old digispark-clone without bootloader (any more) and as I wrote, I tried to upgrade by ATTinyCore /  ...

**Comment by SpenceKonde** [comment]
Does that issue happen on my core too? That sort of thing has happened a lot due to the mess in boards.txt, and is why the next phase of my work on ATTinyCore 2.0.0 is refactoring boards.txt and makiing a maintainable solution for it....

**Comment by ArminJo** [comment]
I organized it now -taking your configuration as model- on my boards.txt the following way:
```
digispark-pro.menu.micronucleus.default=Default (14970 bytes avail.)
digispark-pro.menu.micronucleus.default.upload.maximum_size=14970
digispark-pro.menu.micronucleus.default.bootloader.file=upgrade-t167_default.hex
digispark-pro.menu.micronucleus.recommended=Recommended (14970 bytes avail.)
digispark-pro.menu.micronucleus.recommended.upload.maximum_size=14970
digispark-pro.menu.micronucleus.recommended.bootloader.file=upgrade-t167_entry_on_powerOn_activePullup_fastExit.hex
digispark-pro.menu.micronucleus.entryReset=Entry on reset (14970 bytes avail.)
digispark-pro.menu.micronucleus.entryReset.upload.maximum_size=14970
digispark-pro.menu.micronucleus.entryReset.bootloader.file=upgrade-t167_entry_on_reset_activePullup_fastExit.hex

digispark-pro.menu.burnmode.upgrade=Upgrade (via USB)
digispark-pro.menu.burnmode.upgrade.bootloader.tool=micronucleus
digispark-pro.menu.burnmode.install=Fresh Install (via ISP)
digispark-pro.menu.burnmode.install.bootloader.tool=avrdude
```

**Comment by pcfreak1201** [comment]
> Does that issue happen on my core too?

Hi Spence!
Yes, it happens with your actual core (because of missing possibilities in Armins core).
But I haven't inspected it yet, and it seems to be only the verify?!

**Comment by ArminJo** [comment]
> because of missing possibilities in Armins core

Can you specify these missing possibilities so I can add them?

**Comment by pcfreak1201** [comment]
I think you already did it (adding Burn Bootloader with external Programmer) :-)

**Comment by pcfreak1201** [comment]
By the way, `-Uefuse:w:0xFE:m -Uhfuse:w:0b11011{bootloader.bod_bits}:m -Ulfuse:w:0xF1:m` still doesn't work, until I set it manual to `E:0xFE H:0xDC L:0xF1`

**Pull request closed without merging**
